server:
  port: 8099
  ssl:
#   注释   one-way authentication (server-auth)
    key-store: classpath:tomcat.keystore
    key-store-password: 123456
#    注释  two-way authentication (add BasicTest-auth)
#    trust-store: classpath:tomcat.keystore
#    trust-store-password: 123456
#    BasicTest-auth: need

spring:
  resources:
    static-locations: classpath:/static
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:mysql://39.106.134.138:3306/xiaofang_liumingfang?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ArlenAndFlyingTiger_117915
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

platformIp: 180.101.147.89
platformPort: 8743
appId: HO8dA35cedLKYb7otoL6ESnDiEca
secret: gWw6N0g_iKvZBgBBtm6scc2au1Ua

#the value of newCaFile and newClientCertFile should not be the same as "ca.jks" or "outgoing.CertwithKey.pkcs12"
newCaFile:
newCaPassword:
newClientCertFile:
newClientCertPassword:
#hostNameVerify default value is true, true means setting STRICT_HOSTNAME_VERIFIER, false means setting ALLOW_ALL_HOSTNAME_VERIFIER
hostNameVerify: true

test: 50FE6401E867A34BD533FE67BB85EDABFED62CEA9D8E3F5516E7B48D01F21A5F
