server:
  port: 8080
spring:
  application:
    name: web
  profiles:
    active: dist
  resources:
    static-locations: classpath:/static
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:mysql://182.61.48.200/telecom?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qdc#@&oiwedadf##%WUIQ
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
